export const BALANCE_VERSION = 4;

export const HOURS_PER_MONTH = 730;
export const BANDWIDTH_USD_PER_GBPS_MONTH = 85;
export const COOLING_OVERHEAD_RATIO = 0.3;
export const STARTING_CASH = 2_500_000;
export const MARKET_REFRESH_SIZE = 6;
export const CONTRACT_TERM_DISCOUNT_BASELINE_MONTHS = 6;
export const CONTRACT_TERM_DISCOUNT_PER_EXTRA_MONTH = 0.02;
export const CONTRACT_TERM_DISCOUNT_FLOOR = 0.68;
