import assert from "node:assert/strict";
import { newGame, summarizeLeaderboardFromState } from "@datacenter-tycoon/game-logic";
import { test } from "bun:test";
import type { RegisterPlayerInput } from "../players/repository.js";
import { InMemoryPlayersRepository, type PlayersRepository } from "../players/repository.js";
import type { RateLimiter, RateLimitRule } from "../rate-limit/fixed-window.js";
import {
  InMemoryLeaderboardRepository,
  type LeaderboardRepository,
} from "../leaderboard/repository.js";
import { apiRequest, createTestApp } from "../test-utils/app.js";

async function registerPlayer(app: ReturnType<typeof createTestApp>["app"]) {
  const response = await apiRequest<{ playerId: string; username: string }>(app, "/players", {
    method: "POST",
    body: JSON.stringify({ username: "Acme Cloud" }),
    headers: { "content-type": "application/json" },
  });

  return response.json;
}

function createLeaderboardApp(options?: {
  players?: PlayersRepository;
  leaderboard?: LeaderboardRepository;
  rateLimiter?: RateLimiter;
}) {
  return createTestApp({
    services: {
      players: options?.players ?? new InMemoryPlayersRepository(),
      leaderboard: options?.leaderboard ?? new InMemoryLeaderboardRepository(),
      rateLimiter: options?.rateLimiter,
    },
  });
}

test("POST /leaderboard/runs stores a run summary", async () => {
  const { app } = createLeaderboardApp();
  const player = await registerPlayer(app);
  const { response, json } = await apiRequest<{
    created: boolean;
    run: {
      runId: string;
      playerId: string;
      clientRunId: string;
      metrics: { money: number; cumulativeRevenue: number; totalServers: number };
      gameMonth: number;
      submittedAt: string;
      updatedAt: string;
    };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-001",
      metrics: {
        money: 1_250_000,
        cumulativeRevenue: 2_750_000,
        totalServers: 12,
        computeCapacity: 160,
        memoryCapacity: 2048,
        storageCapacity: 800,
        gpuCapacity: 24,
      },
      gameMonth: 18,
    }),
  });

  assert.equal(response.status, 201);
  assert.equal(json?.created, true);
  assert.match(json?.run.runId ?? "", /^run_[a-f0-9]{32}$/);
  assert.equal(json?.run.playerId, player?.playerId);
  assert.equal(json?.run.clientRunId, "run-001");
  assert.equal(json?.run.metrics.money, 1_250_000);
  assert.equal(json?.run.gameMonth, 18);
});

test("POST /leaderboard/runs accepts payloads generated by the shared game-logic helper", async () => {
  const { app } = createLeaderboardApp();
  const player = await registerPlayer(app);
  const state = newGame(5678, { playerName: "Acme Cloud" });
  state.tick = 4;
  state.player.cash = 1_420_000;
  const summary = summarizeLeaderboardFromState(state);

  const { response, json } = await apiRequest<{
    created: boolean;
    run: {
      playerId: string;
      clientRunId: string;
      metrics: { money: number; cumulativeRevenue: number };
      gameMonth: number;
    };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: summary.gameId,
      metrics: summary.metrics,
      gameMonth: summary.gameMonth,
    }),
  });

  assert.equal(response.status, 201);
  assert.equal(json?.created, true);
  assert.equal(json?.run.playerId, player?.playerId);
  assert.equal(json?.run.clientRunId, summary.gameId);
  assert.equal(json?.run.metrics.money, 1_420_000);
  assert.equal(json?.run.gameMonth, 4);
});

test("POST /leaderboard/runs is idempotent for duplicate client run ids", async () => {
  const { app } = createLeaderboardApp();
  const player = await registerPlayer(app);
  const payload = {
    playerId: player?.playerId,
    clientRunId: "run-duplicate",
    metrics: {
      money: 900_000,
      cumulativeRevenue: 1_100_000,
      totalServers: 8,
      computeCapacity: 80,
      memoryCapacity: 512,
      storageCapacity: 256,
      gpuCapacity: 0,
    },
    gameMonth: 11,
  };

  const first = await apiRequest<{ created: boolean; run: { runId: string } }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  });
  const second = await apiRequest<{ created: boolean; run: { runId: string } }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(payload),
  });

  assert.equal(first.response.status, 201);
  assert.equal(second.response.status, 200);
  assert.equal(first.json?.created, true);
  assert.equal(second.json?.created, false);
  assert.equal(first.json?.run.runId, second.json?.run.runId);
});

test("POST /leaderboard/runs rejects unknown player ids", async () => {
  const { app } = createLeaderboardApp();
  const { response, json } = await apiRequest<{
    error: { code: string; message: string };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: "player_missing",
      clientRunId: "run-404",
      metrics: {
        money: 1,
        cumulativeRevenue: 1,
        totalServers: 1,
        computeCapacity: 1,
        memoryCapacity: 1,
        storageCapacity: 1,
        gpuCapacity: 1,
      },
      gameMonth: 1,
    }),
  });

  assert.equal(response.status, 404);
  assert.equal(json?.error.code, "PLAYER_NOT_FOUND");
});

test("POST /leaderboard/runs rejects invalid metric payloads", async () => {
  const { app } = createLeaderboardApp();
  const player = await registerPlayer(app);
  const { response, json } = await apiRequest<{
    error: { code: string; message: string };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-invalid",
      metrics: {
        money: -1,
        cumulativeRevenue: 1,
        totalServers: 1,
        computeCapacity: 1,
        memoryCapacity: 1,
        storageCapacity: 1,
        gpuCapacity: 1,
      },
      gameMonth: 1,
    }),
  });

  assert.equal(response.status, 400);
  assert.equal(json?.error.code, "INVALID_LEADERBOARD_SUBMISSION");
});

test("POST /leaderboard/runs updates the stored run when the same client run progresses", async () => {
  const { app } = createLeaderboardApp();
  const player = await registerPlayer(app);

  await apiRequest(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-progress",
      metrics: {
        money: 10,
        cumulativeRevenue: 10,
        totalServers: 1,
        computeCapacity: 10,
        memoryCapacity: 10,
        storageCapacity: 10,
        gpuCapacity: 0,
      },
      gameMonth: 1,
    }),
  });

  const { response, json } = await apiRequest<{
    created: boolean;
    run: {
      metrics: { money: number; cumulativeRevenue: number; totalServers: number };
      gameMonth: number;
    };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-progress",
      metrics: {
        money: 999,
        cumulativeRevenue: 25,
        totalServers: 2,
        computeCapacity: 20,
        memoryCapacity: 10,
        storageCapacity: 10,
        gpuCapacity: 0,
      },
      gameMonth: 2,
    }),
  });

  assert.equal(response.status, 200);
  assert.equal(json?.created, false);
  assert.equal(json?.run.metrics.money, 999);
  assert.equal(json?.run.metrics.cumulativeRevenue, 25);
  assert.equal(json?.run.gameMonth, 2);
});

test("POST /leaderboard/runs rejects non-monotonic retries for the same client run id", async () => {
  const { app } = createLeaderboardApp();
  const player = await registerPlayer(app);

  await apiRequest(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-conflict",
      metrics: {
        money: 10,
        cumulativeRevenue: 10,
        totalServers: 1,
        computeCapacity: 10,
        memoryCapacity: 10,
        storageCapacity: 10,
        gpuCapacity: 0,
      },
      gameMonth: 2,
    }),
  });

  const { response, json } = await apiRequest<{
    error: { code: string; message: string };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-conflict",
      metrics: {
        money: 999,
        cumulativeRevenue: 9,
        totalServers: 1,
        computeCapacity: 10,
        memoryCapacity: 10,
        storageCapacity: 10,
        gpuCapacity: 0,
      },
      gameMonth: 1,
    }),
  });

  assert.equal(response.status, 409);
  assert.equal(json?.error.code, "NON_MONOTONIC_RUN_UPDATE");
});

test("POST /leaderboard/runs surfaces database failures as internal errors", async () => {
  class BrokenLeaderboardRepository implements LeaderboardRepository {
    async upsertRun(): Promise<never> {
      throw new Error("database unavailable");
    }
  }

  const players = new InMemoryPlayersRepository();
  const createdPlayer = await players.createPlayer({ username: "Acme Cloud" });
  const { app } = createLeaderboardApp({
    players,
    leaderboard: new BrokenLeaderboardRepository(),
  });
  const { response, json } = await apiRequest<{
    error: { code: string; message: string };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      playerId: createdPlayer.playerId,
      clientRunId: "run-broken",
      metrics: {
        money: 1,
        cumulativeRevenue: 1,
        totalServers: 1,
        computeCapacity: 1,
        memoryCapacity: 1,
        storageCapacity: 1,
        gpuCapacity: 1,
      },
      gameMonth: 1,
    }),
  });

  assert.equal(response.status, 500);
  assert.equal(json?.error.code, "INTERNAL_SERVER_ERROR");
  assert.match(json?.error.message ?? "", /database unavailable/);
});

test("GET /leaderboard returns ranked entries for a selected metric", async () => {
  const players = new InMemoryPlayersRepository();
  const leaderboard = new InMemoryLeaderboardRepository();
  const alpha = await players.createPlayer({ username: "Alpha Cloud" });
  const beta = await players.createPlayer({ username: "Beta Cloud" });
  const gamma = await players.createPlayer({ username: "Gamma Cloud" });

  await leaderboard.upsertRun({
    playerId: beta.playerId,
    clientRunId: "run-beta",
    metrics: {
      money: 950,
      cumulativeRevenue: 1_400,
      totalServers: 9,
      computeCapacity: 50,
      memoryCapacity: 300,
      storageCapacity: 200,
      gpuCapacity: 0,
    },
    gameMonth: 9,
  });
  await leaderboard.upsertRun({
    playerId: gamma.playerId,
    clientRunId: "run-gamma",
    metrics: {
      money: 700,
      cumulativeRevenue: 1_900,
      totalServers: 7,
      computeCapacity: 30,
      memoryCapacity: 250,
      storageCapacity: 220,
      gpuCapacity: 10,
    },
    gameMonth: 8,
  });
  await leaderboard.upsertRun({
    playerId: alpha.playerId,
    clientRunId: "run-alpha",
    metrics: {
      money: 1_200,
      cumulativeRevenue: 1_100,
      totalServers: 6,
      computeCapacity: 40,
      memoryCapacity: 200,
      storageCapacity: 100,
      gpuCapacity: 0,
    },
    gameMonth: 7,
  });

  const { app } = createLeaderboardApp({ players, leaderboard });
  const { response, json } = await apiRequest<{
    metric: string;
    period: string;
    limit: number;
    entries: Array<{ rank: number; username: string; value: number }>;
  }>(app, "/leaderboard?metric=money&period=all-time&limit=2");

  assert.equal(response.status, 200);
  assert.equal(json?.metric, "money");
  assert.equal(json?.limit, 2);
  assert.deepEqual(json?.entries.map((entry) => ({
    rank: entry.rank,
    username: entry.username,
    value: entry.value,
  })), [
    { rank: 1, username: "Alpha Cloud", value: 1_200 },
    { rank: 2, username: "Beta Cloud", value: 950 },
  ]);
});

test("GET /leaderboard applies deterministic tie-breaking for equal metric values", async () => {
  const fixedSubmittedAt = new Date("2026-05-18T12:00:00.000Z");
  const players = new InMemoryPlayersRepository();
  const leaderboard = new InMemoryLeaderboardRepository(() => fixedSubmittedAt);
  const alpha = await players.createPlayer({ username: "Alpha Cloud" });
  const bravo = await players.createPlayer({ username: "Bravo Cloud" });

  await leaderboard.upsertRun({
    playerId: bravo.playerId,
    clientRunId: "bravo-run",
    metrics: {
      money: 500,
      cumulativeRevenue: 500,
      totalServers: 5,
      computeCapacity: 10,
      memoryCapacity: 20,
      storageCapacity: 30,
      gpuCapacity: 0,
    },
    gameMonth: 5,
  });
  await leaderboard.upsertRun({
    playerId: alpha.playerId,
    clientRunId: "alpha-run",
    metrics: {
      money: 500,
      cumulativeRevenue: 500,
      totalServers: 5,
      computeCapacity: 10,
      memoryCapacity: 20,
      storageCapacity: 30,
      gpuCapacity: 0,
    },
    gameMonth: 5,
  });

  const { app } = createLeaderboardApp({ players, leaderboard });
  const { response, json } = await apiRequest<{
    entries: Array<{ rank: number; username: string; value: number }>;
  }>(app, "/leaderboard?metric=money&period=all-time&limit=5");

  assert.equal(response.status, 200);
  assert.deepEqual(json?.entries.map((entry) => entry.username), [
    "Alpha Cloud",
    "Bravo Cloud",
  ]);
});

test("GET /leaderboard rejects invalid query parameters", async () => {
  const { app } = createLeaderboardApp();
  const { response, json } = await apiRequest<{
    error: { code: string; message: string };
  }>(app, "/leaderboard?metric=bogus&period=all-time&limit=10");

  assert.equal(response.status, 400);
  assert.equal(json?.error.code, "INVALID_LEADERBOARD_QUERY");
});

test("POST /leaderboard/runs rate-limits repeated submissions from the same client", async () => {
  class DenyAllRateLimiter implements RateLimiter {
    consume(_scope: string, _key: string, _rule: RateLimitRule) {
      return {
        allowed: false,
        retryAfterSeconds: 15,
        remaining: 0,
      };
    }
  }

  const { app } = createLeaderboardApp({
    rateLimiter: new DenyAllRateLimiter(),
  });
  const player = await registerPlayer(app);
  const { response, json } = await apiRequest<{
    error: { code: string; message: string };
  }>(app, "/leaderboard/runs", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-forwarded-for": "198.51.100.24",
    },
    body: JSON.stringify({
      playerId: player?.playerId,
      clientRunId: "run-limited",
      metrics: {
        money: 1,
        cumulativeRevenue: 1,
        totalServers: 1,
        computeCapacity: 1,
        memoryCapacity: 1,
        storageCapacity: 1,
        gpuCapacity: 1,
      },
      gameMonth: 1,
    }),
  });

  assert.equal(response.status, 429);
  assert.equal(json?.error.code, "RATE_LIMITED");
  assert.match(json?.error.message ?? "", /Retry after 15 seconds/);
});

test("service-level register input types remain usable in fake repositories", async () => {
  const sampleInput: RegisterPlayerInput = {
    username: "Acme Cloud",
  };

  assert.equal(sampleInput.username, "Acme Cloud");
});
