import type { Region, RegionId } from "../types.js";

const regionId = (value: string): RegionId => value as RegionId;

export const REGION_CATALOG: Record<string, Region> = {
	us_east: {
		id: regionId("us_east"),
		name: "US East",
		code: "IAD",
		city: "Ashburn",
		coordinates: { x: 26, y: 35 },
		powerCostPerKwh: 0.07,
		staffWage: 6_500,
		taxRate: 0.06,
		totalPowerAvailable: 10_000,
		totalStaffAvailable: 800,
		powerUsed: 0,
		staffUsed: 0,
	},
	us_west: {
		id: regionId("us_west"),
		name: "US West",
		code: "PDX",
		city: "Boardman",
		coordinates: { x: 15, y: 33 },
		powerCostPerKwh: 0.05,
		staffWage: 5_800,
		taxRate: 0.07,
		totalPowerAvailable: 8_000,
		totalStaffAvailable: 400,
		powerUsed: 0,
		staffUsed: 0,
	},
	eu_west: {
		id: regionId("eu_west"),
		name: "EU West",
		code: "DUB",
		city: "Dublin",
		coordinates: { x: 44, y: 28 },
		powerCostPerKwh: 0.12,
		staffWage: 5_200,
		taxRate: 0.125,
		totalPowerAvailable: 5_000,
		totalStaffAvailable: 350,
		powerUsed: 0,
		staffUsed: 0,
	},
	eu_central: {
		id: regionId("eu_central"),
		name: "EU Central",
		code: "FRA",
		city: "Frankfurt",
		coordinates: { x: 48, y: 30 },
		powerCostPerKwh: 0.18,
		staffWage: 6_200,
		taxRate: 0.28,
		totalPowerAvailable: 6_000,
		totalStaffAvailable: 450,
		powerUsed: 0,
		staffUsed: 0,
	},
	ap_northeast: {
		id: regionId("ap_northeast"),
		name: "AP Northeast",
		code: "NRT",
		city: "Tokyo",
		coordinates: { x: 88, y: 36 },
		powerCostPerKwh: 0.15,
		staffWage: 5_800,
		taxRate: 0.22,
		totalPowerAvailable: 4_500,
		totalStaffAvailable: 400,
		powerUsed: 0,
		staffUsed: 0,
	},
	ap_southeast: {
		id: regionId("ap_southeast"),
		name: "AP Southeast",
		code: "SIN",
		city: "Singapore",
		coordinates: { x: 79, y: 55 },
		powerCostPerKwh: 0.16,
		staffWage: 5_500,
		taxRate: 0.17,
		totalPowerAvailable: 4_000,
		totalStaffAvailable: 350,
		powerUsed: 0,
		staffUsed: 0,
	},
	sa_east: {
		id: regionId("sa_east"),
		name: "SA East",
		code: "GRU",
		city: "São Paulo",
		coordinates: { x: 33, y: 65 },
		powerCostPerKwh: 0.13,
		staffWage: 3_500,
		taxRate: 0.34,
		totalPowerAvailable: 3_500,
		totalStaffAvailable: 450,
		powerUsed: 0,
		staffUsed: 0,
	},
	me_central: {
		id: regionId("me_central"),
		name: "ME Central",
		code: "DXB",
		city: "Dubai",
		coordinates: { x: 61, y: 43 },
		powerCostPerKwh: 0.08,
		staffWage: 4_800,
		taxRate: 0.09,
		totalPowerAvailable: 5_500,
		totalStaffAvailable: 300,
		powerUsed: 0,
		staffUsed: 0,
	},
};
