import type { Region, RegionId } from "../types.js";

const regionId = (value: string): RegionId => value as RegionId;

export const REGION_CATALOG: Record<string, Region> = {
	silicon_valley: {
		id: regionId("silicon_valley"),
		name: "Silicon Valley",
		powerCostPerKwh: 0.22,
		staffWage: 9_500,
		taxRate: 0.21,
		totalPowerAvailable: 5_000,
		totalStaffAvailable: 500,
		powerUsed: 0,
		staffUsed: 0,
	},
	iowa: {
		id: regionId("iowa"),
		name: "Iowa",
		powerCostPerKwh: 0.06,
		staffWage: 4_200,
		taxRate: 0.08,
		totalPowerAvailable: 8_000,
		totalStaffAvailable: 300,
		powerUsed: 0,
		staffUsed: 0,
	},
	iceland: {
		id: regionId("iceland"),
		name: "Iceland",
		powerCostPerKwh: 0.04,
		staffWage: 5_800,
		taxRate: 0.15,
		totalPowerAvailable: 3_000,
		totalStaffAvailable: 120,
		powerUsed: 0,
		staffUsed: 0,
	},
	frankfurt: {
		id: regionId("frankfurt"),
		name: "Frankfurt",
		powerCostPerKwh: 0.18,
		staffWage: 6_200,
		taxRate: 0.28,
		totalPowerAvailable: 6_000,
		totalStaffAvailable: 400,
		powerUsed: 0,
		staffUsed: 0,
	},
	singapore: {
		id: regionId("singapore"),
		name: "Singapore",
		powerCostPerKwh: 0.16,
		staffWage: 5_500,
		taxRate: 0.17,
		totalPowerAvailable: 4_000,
		totalStaffAvailable: 350,
		powerUsed: 0,
		staffUsed: 0,
	},
	mumbai: {
		id: regionId("mumbai"),
		name: "Mumbai",
		powerCostPerKwh: 0.09,
		staffWage: 2_800,
		taxRate: 0.25,
		totalPowerAvailable: 4_500,
		totalStaffAvailable: 600,
		powerUsed: 0,
		staffUsed: 0,
	},
	sao_paulo: {
		id: regionId("sao_paulo"),
		name: "São Paulo",
		powerCostPerKwh: 0.13,
		staffWage: 3_500,
		taxRate: 0.34,
		totalPowerAvailable: 3_500,
		totalStaffAvailable: 450,
		powerUsed: 0,
		staffUsed: 0,
	},
	sydney: {
		id: regionId("sydney"),
		name: "Sydney",
		powerCostPerKwh: 0.19,
		staffWage: 7_200,
		taxRate: 0.30,
		totalPowerAvailable: 2_500,
		totalStaffAvailable: 200,
		powerUsed: 0,
		staffUsed: 0,
	},
	dubai: {
		id: regionId("dubai"),
		name: "Dubai",
		powerCostPerKwh: 0.08,
		staffWage: 4_800,
		taxRate: 0.09,
		totalPowerAvailable: 5_500,
		totalStaffAvailable: 280,
		powerUsed: 0,
		staffUsed: 0,
	},
	seoul: {
		id: regionId("seoul"),
		name: "Seoul",
		powerCostPerKwh: 0.11,
		staffWage: 5_200,
		taxRate: 0.22,
		totalPowerAvailable: 4_000,
		totalStaffAvailable: 380,
		powerUsed: 0,
		staffUsed: 0,
	},
};
